## 本地测试

### 1. 打印日志

在开发过程中，打印日志会是很重要的调试手段，可以将如下代码加入到 `main.py` 实现日志输出：

```python
import logging
logging.basicConfig()
logger = logging.getLogger("lev")
logger.setLevel(logging.DEBUG)
logger.debug("[lev app - hello world] debug test")
```

完整的 `main.py` 代码如下：

```python
import levrt
from lev.whtcjdtc2008.hello_world import hello

async def main():
    doc = await hello.exp(9)
    data = await doc.get()
    print(data["msg"])


if __name__ == "__main__":
    import logging
    logging.basicConfig()
    logger = logging.getLogger("lev")
    logger.setLevel(logging.DEBUG)
    logger.debug("[lev app - hello world] debug test")
    levrt.run(main())
```

使用 `pdm run python main.py` 运行，可以看到日志已经被打印到终端：

```bash
┌─[hunter@192] - [~/Workspace/lev_hub/whtcjdtc2008.hello_world] - [10085]
└─[$] pdm run python main.py                                                                                                                [12:02:24]
DEBUG:lev:[lev app - hello world] debug test
INFO:lev:job: whtcjdtc2008 main 711
INFO:lev:progress: 0.0
INFO:lev:progress: 0.25
2.718281828
```

### 2. 调试器

在开发过程中，仅仅凭借日志是很难准确高效解决问题的，这时候调试器就会成为重要的帮手。

这里我们使用 [PyCharm](https://www.jetbrains.com/pycharm/) 来进行动态调试。

### 3. 容器日志

### 4. 容器静态分析
如果想查看容器内部的文件，使用 `docker cp` 命令，而非直接使用 `docker start` 启动容器。

重新启动容器，会让任务重新执行，进而影响上一次的输出结果。

### 5. 容器动态调试

### 6. 异常失败原因排查

在测试过程中可能会遇到失败的情况，有很多原因，下面列举常见的几种：

1. Connect call failed ('127.0.0.1', 38379)

   因为 docker 本身的缺陷，在计算机睡眠之后，容器之间无法互相访问，需要重新启动 docker 服务

   也有可能会导致下面设备离线

2. 设备离线

   agent 无法连接服务器，需要执行 `ssh lev agent | sudo docker run -v /var/run/docker.sock:/docker --rm -i talentsec/lev` 命令，重新拉取执行 agent
